### PR TITLE
RFC: Extend Handler to store in Dict container

### PR DESCRIPTION
**Pull request by glennmoy**
May just be easier to make a new handler type altogether but this isn't a breaking change, all I had to do was relax the type parameter.

MWE, using example checkpoint in Package.jl:
```julia
Checkpoint.checkpoint("Package", "example", :data => data, :metadata => metadata; name="bar")
```
```julia
# global Dict performs as the sink for the checkpoints rather than a filepath
const RECORD = Dict{String,Dict}()

Checkpoints.config(Handler(RECORD), ["Package.example"])

with_checkpoint_tag((:foo=1,)) do 
    run()
end
```

post-progam, `RECORD` is a nested dict where keys are elements of the `path(handler, name)`.
the final entry lists the checkpoint data we saved:
```julia
julia> RECORD
Dict{String, Dict} with 1 entry:
"name=bar" => Dict{String,Dict}("Package" => Dict{String,Dict}("example" => Dict{Symbol,Array}(:data => data, :metadata => metadata)))
```

### CODE REVIEW

**Comment by oxinabox** [comment]
Adding a new Handler type is also not breaking.
Maybe we would like to deprecate the name `Handler` to be `JLSOHandler`
and introduce `AbstractHandler` as a common supertype.

**Comment by rofinn** [comment]
Yeah, I think a separate handler would be cleaner. Might also need to see this in action first. My understanding is that you'd just manually handle writing the dict values after everything has been checkpointed into the dict?

**Comment by glennmoy** [comment]
> Adding a new Handler type is also not breaking. Maybe we would like to deprecate the name `Handler` to be `JLSOHandler` and introduce `AbstractHandler` as a common supertype.

Yeah I wasn't sure which was preferable - I guess a new handler is cleaner but it would add extra work for making the AbstractHandler

**Comment by glennmoy** [comment]
> Yeah, I think a separate handler would be cleaner. Might also need to see this in action first. My understanding is that you'd just manually handle writing the dict values after everything has been checkpointed into the dict?

No, it shouldn't require manually writing unless I'm misunderstanding something? See example above, it should work just like saving to a `filepath` except the "path" determines the branches in the global Dict.

There may be another, better way of doing this but this was my initial idea for implementing.

**Comment by rofinn** [comment]
> I don't think it should require manually writing unless I'm misunderstanding something?

I mean that once you've run your program and populated the dictionary with checkpointed objects it's up to the user what to do with it (ie: writing states to disk, database, etc).

**Pull request closed without merging**
